// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odemfyuwaasfhtpnkhei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZW1meXV3YWFzZmh0cG5raGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjEzMjEsImV4cCI6MjA2MzM5NzMyMX0.4ENgLVH543zNpaea295oDXNioIU4v0YPU17csJSel74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);